apply-ghc-options: everything
ghc-options:
  $everything: -optc -Wno-unused-command-line-argument
flags: {}
extra-package-dbs: []
packages:
- '.'
- location: languages/go
  extra-dep: true
- location: languages/php
  extra-dep: true
- location: languages/python
  extra-dep: true
- location: languages/typescript
  extra-dep: true
- location: languages/json
  extra-dep: true
- location: languages/ruby
  extra-dep: true
resolver: nightly-2018-04-25
